name: Build Custom Atlantis Image

on:
  workflow_dispatch:

jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./setup/atlantis/custom-image
          push: true
          tags: quay.io/elostech/atlantis-custom-image:${{ github.run_number }}